### ISSUE TITLE
Integration with Laravel

### ISSUE THREAD

**Issue by FabioSTI** [devvoh/fixed-width#5]
Hi. I'm having issues integratin this library with Laravel 7.
After requiring it with composer (and update/dump-auto) I get:
```

Error
Class 'Devvoh\FixedWidth\Schema' not found
```

I'm using 

`use Devvoh\FixedWidth\Schema;`

at the top of the controller (tried also with a closure in a route)

Any help would be appreciated.

**Comment by wilsenhc** [comment]
The PSR-4 autoload generation is broken because the namespaces don't match

Just sent a commit fixing that

**Comment by m-lopez-f** [comment]
Sorry but your fixed does't work properly, I create a new PR  #10. I hope fixed the problem
